# Generated by Django 2.0.6 on 2018-06-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(max_length=2000, upload_to='')),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
