# Generated by Django 2.0.6 on 2018-06-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(max_length=2000, upload_to='')),
                ('team_id', models.IntegerField()),
                ('high_score', models.IntegerField()),
            ],
        ),
    ]
